const Terms = () => {
  return <div className="min-h-screen bg-background py-20 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-8 text-brand-navy">Terms of Service</h1>

        <p className="mb-6"><strong>Last Updated:</strong> January 18, 2025</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Use of Our Services</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>Services must only be used for lawful purposes.</li>
          <li>You may not interfere with or disrupt the security or functionality of our systems.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Intellectual Property</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>All content, trademarks, logos, and intellectual property on this site are owned by Mullins Digital Ventures LLC.</li>
          <li>Content may not be used without prior written permission.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Limitation of Liability</h2>
        <p className="mb-6">We are not liable for any indirect, incidental, or consequential damages arising from your use of our website or services. All services are provided "as is" without warranties of any kind.
This includes any content or outputs generated by artificial intelligence (“AI”), which are provided “as is” without warranties of accuracy, reliability, or fitness for a particular purpose.</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Termination</h2>
        <p className="mb-6">
          We reserve the right to suspend or terminate your access if you violate these Terms or engage in harmful activities.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Governing Law</h2>
        <p className="mb-6">
          These Terms are governed by the laws of the State of Wyoming, USA. Any disputes will be resolved in the appropriate courts of Wyoming.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
        <p className="mb-6">
          For questions about these Terms, please contact us:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Email:</strong> admin@mullinsdigitalventures.com</li>
          <li><strong>Address:</strong> Mullins Digital Ventures LLC, Wyoming, USA</li>
        </ul>

        <p className="mt-8">
          We may update these Terms of Service periodically. Updates will be posted on this page with a revised effective date.
        </p>

        <p className="mt-8">
          <a href="/" className="text-brand-blue hover:text-brand-navy smooth-transition">
            ← Return to Home
          </a>
        </p>
      </div>
    </div>;
};
export default Terms;